### ISSUE TITLE
Doesn't install the plugin on npm command

### ISSUE THREAD

**Issue by princerafid01** [cyrusstoller/vue-plaid-link#1]
The `npm install --save vue-plaid-link` doesn't install the plugin.

**Comment by cyrusstoller** [comment]
Apologies for the confusion, this package hasn't been published on npm. I think you're looking for this repository instead: https://github.com/roundupapp/vue-plaid-link

**Comment by cyrusstoller** [comment]
If you'd like to use this package, I uploaded it npm. You should be able to do:

```
npm install --save vue-plaid-link2
```
