### ISSUE TITLE
Testing module / banks missing

### ISSUE THREAD

**Issue by leostereo** [cyrusstoller/vue-plaid-link#11]
Hi guys , after installing the module and submiting the generated link token, I got the bank list to login but noticed that  there are some banks missing , when comparing with the plaid quickstart application , for example , chase bank is not on the menu , and when manually looking into it , it does not appear.
Am I missing something ? 
I just toke your code and changed the link_token.
Thanks!

**Comment by cyrusstoller** [comment]
Can you provide a gist of the code you're using? Happy to take a look.

**Comment by leostereo** [comment]
Dear Cyruss.
I toke the example you provided and run without change anything and worked
properly.
but then I tried replacing your public_key for my link_token (according to
plaid docs , public key is not longer supported)
It does work but I got a very different banks list.

The code seems to be ok, I really appreciate your help on this, let me ask
plaid support what is wrong with my link_token and then I will let you know.
Thanks!!
Leandro.

**Comment by cyrusstoller** [comment]
Public_keys are no longer supported (it's been retained it this vue component for legacy reasons). Did you try leaving that argument out, so that it looks something like --

```vue
<PlaidLink
  clientName="APPLICATION NAME"
  env="sandbox"
  link_token="GENERATED LINK TOKEN"
  :products="['auth','transactions']"
  webhook="https://requestb.in"
  :onLoad='onLoad'
  :onSuccess='onSuccess'
  :onExit='onExit'
  :onEvent='onEvent'
  >
  <button>Open Link Slot</button>
</PlaidLink>
```

**Comment by cyrusstoller** [comment]
Glad you have it sorted out.
