### ISSUE TITLE
Prevent event callbacks being triggered 2 times

### ISSUE THREAD

**Issue by sneko** [cyrusstoller/vue-plaid-link#13]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `vue-plaid-link2@0.2.1` for the project I'm working on.

Hi @cyrusstoller ,

When navigating across my app I saw Plaid was triggering X times the appropriate callback (e.g. in case of success, `onSucces`).

After investigation it seems due to the script being loaded each time your plugin is mounted, some subscribers persist even if your plugin component is destroyed (I saw this with a `beforeDestroy()`.

The workaround for me is to prevent downloading multiple times the Plaid script... moreover it will help a bit on performance.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vue-plaid-link2/PlaidLink.vue b/node_modules/vue-plaid-link2/PlaidLink.vue
index 027b1e1..ea4acb2 100644
--- a/node_modules/vue-plaid-link2/PlaidLink.vue
+++ b/node_modules/vue-plaid-link2/PlaidLink.vue
@@ -119,6 +119,12 @@ export default {
     }
   },
   mounted() {
+    // Only download the script if not already done
+    if (window.Plaid) {
+      this.plaid = window.Plaid
+      return
+    }
+
     let linkScript = document.createElement('script')
     linkScript.async = true
     linkScript.setAttribute('src', 'https://cdn.plaid.com/link/v2/stable/link-initialize.js')
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by cyrusstoller** [comment]
Thanks for this patch suggestion! Apologies for the slow response. This is updated in v0.2.2.
