### ISSUE TITLE
Link Token instead of Public Key

### ISSUE THREAD

**Issue by samgabrail** [cyrusstoller/vue-plaid-link#5]
Hello! Is there a plan to update this package to support the new Link Token flow as [described here?](https://plaid.com/docs/link/link-token-migration-guide/#introduction)

**Comment by cyrusstoller** [comment]
Apologies - I don't quite follow your question.

This is meant to follow https://plaid.com/docs/link/web/

**Comment by samgabrail** [comment]
@cyrusstoller thanks for your quick reply. Plaid has recently deprecated the use of public keys. They introduced a new link_token, which replaces the static public_key. Please see below. So I'm wondering if there is a plan to update this package to support this new link token.
https://plaid.com/docs/link/web/#link-web-create-key
https://plaid.com/docs/link/link-token-migration-guide

**Comment by cyrusstoller** [comment]
Ah! Thanks for clarifying.

I should have time to update in the next few days. If you have time to submit a PR before then, I'm also happy to review and merge.

**Comment by samgabrail** [comment]
thank you!

**Comment by cyrusstoller** [comment]
Just pushed v0.2.0 with Link Token support. Let me know if you run into any issues.

**Comment by samgabrail** [comment]
Thank you, works well!

**Comment by cyrusstoller** [comment]
Awesome. Glad to hear it. Let me know if anything else comes up.
